import { type RouteConfig, index, layout, route } from "@react-router/dev/routes";

export default [
  layout("routes/public/layout.tsx", { id: "public" }, [
    index("routes/public/home.tsx"),
    route("p/:slug", "routes/p.$slug.tsx"),
    route("programs", "routes/public.programs.tsx"),
    route("programs/:slug", "routes/public.programs.$slug.tsx"),
    route("subjects/:slug", "routes/public.subjects.$slug.tsx"),
    route("courses", "routes/public.courses.tsx"),
    route("courses/:slug", "routes/public.courses.$slug.tsx"),
    route("courses/:slug/units/:unitId", "routes/public.courses.$slug.units.$unitId.tsx"),
    route("products/:slug", "routes/public.products.$slug.tsx"),
    route("login", "routes/public/login.tsx"),
    route("register", "routes/public/register.tsx"),
    route("forgot-password", "routes/public/forgot-password.tsx"),
    route("reset-password", "routes/public/reset-password.tsx"),
    route("set-locale", "routes/public/set-locale.tsx"),
  ]),
  route("logout", "routes/logout.tsx"),
  route("theme.css", "routes/theme[.]css.tsx"),
  route("favicon.ico", "routes/favicon[.]ico.tsx"),
  route("learn/:courseSlug/:lessonSlug", "routes/learn.$courseSlug.$lessonSlug.tsx"),
  route("files/:id", "routes/files.$id.tsx"),
  route("api/playback/:videoId", "routes/api.playback.$videoId.tsx"),
  route("beacons/progress", "routes/beacons.progress.tsx"),
  route("api/exam-attempt", "routes/api.exam-attempt.tsx"),
  route("webhooks/payments/:provider", "routes/webhooks.payments.$provider.tsx"),
  route("exams/:slug/attempt", "routes/student/exams.$slug.attempt.tsx"),
  route("api/mock-stream/:videoId/:file", "routes/api.mock-stream.$videoId.$file.tsx"),
  layout("routes/student/layout.tsx", { id: "student" }, [
    route("dashboard", "routes/student/dashboard.tsx"),
    route("profile", "routes/student/profile.tsx"),
    route("exams", "routes/student/exams.tsx"),
    route("exams/:slug", "routes/student/exams.$slug.tsx"),
    route("results", "routes/student/results.tsx"),
    route("results/:attemptId", "routes/student/results.$attemptId.tsx"),
    route("checkout/:productSlug", "routes/student/checkout.$productSlug.tsx"),
    route("orders", "routes/student/orders.tsx"),
    route("orders/:orderNumber", "routes/student/orders.$orderNumber.tsx"),
    route("activate", "routes/student/activate.tsx"),
    route("profile/security", "routes/student/security.tsx"),
    route("notifications", "routes/student/notifications.tsx"),
  ]),
  route("admin", "routes/admin/layout.tsx", { id: "admin-root" }, [
    index("routes/admin/home.tsx"),
    route("cms", "routes/admin.cms.tsx"),
    route("cms/pages/:id", "routes/admin.cms.pages.$id.tsx"),
    route("cms/preview/:pageId", "routes/admin.cms.preview.$pageId.tsx"),
    route("cms/menus", "routes/admin.cms.menus.tsx"),
    route("cms/forms", "routes/admin.cms.forms.tsx"),
    route("appearance", "routes/admin.appearance.tsx"),
    route("content", "routes/admin.content.tsx"),
    route("content/:type/:id", "routes/admin.content.$type.$id.tsx"),
    route("files", "routes/admin.files.tsx"),
    route("videos", "routes/admin.videos.tsx"),
    route("entitlements", "routes/admin.entitlements.tsx"),
    route("users", "routes/admin.users.tsx"),
    route("users/:id", "routes/admin.users.$id.tsx"),
    route("analytics", "routes/admin.analytics.tsx"),
    route("audit", "routes/admin.audit.tsx"),
    route("security", "routes/admin.security.tsx"),
    route("announcements", "routes/admin.announcements.tsx"),
    route("assessment", "routes/admin.assessment.tsx"),
    route("assessment/questions/:id", "routes/admin.assessment.questions.$id.tsx"),
    route("assessment/exams/:id", "routes/admin.assessment.exams.$id.tsx"),
    route("commerce", "routes/admin.commerce.tsx"),
    route("commerce/products/:id", "routes/admin.commerce.products.$id.tsx"),
    route("commerce/orders/:id", "routes/admin.commerce.orders.$id.tsx"),
    route("commerce/batches/:id", "routes/admin.commerce.batches.$id.tsx"),
  ]),
] satisfies RouteConfig;
