// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/p/:slug": {
    params: {
      "slug": string;
    };
  };
  "/programs": {
    params: {};
  };
  "/programs/:slug": {
    params: {
      "slug": string;
    };
  };
  "/subjects/:slug": {
    params: {
      "slug": string;
    };
  };
  "/courses": {
    params: {};
  };
  "/courses/:slug": {
    params: {
      "slug": string;
    };
  };
  "/courses/:slug/units/:unitId": {
    params: {
      "slug": string;
      "unitId": string;
    };
  };
  "/products/:slug": {
    params: {
      "slug": string;
    };
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/set-locale": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/theme.css": {
    params: {};
  };
  "/favicon.ico": {
    params: {};
  };
  "/learn/:courseSlug/:lessonSlug": {
    params: {
      "courseSlug": string;
      "lessonSlug": string;
    };
  };
  "/files/:id": {
    params: {
      "id": string;
    };
  };
  "/api/playback/:videoId": {
    params: {
      "videoId": string;
    };
  };
  "/beacons/progress": {
    params: {};
  };
  "/api/exam-attempt": {
    params: {};
  };
  "/webhooks/payments/:provider": {
    params: {
      "provider": string;
    };
  };
  "/exams/:slug/attempt": {
    params: {
      "slug": string;
    };
  };
  "/api/mock-stream/:videoId/:file": {
    params: {
      "videoId": string;
      "file": string;
    };
  };
  "/dashboard": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/exams": {
    params: {};
  };
  "/exams/:slug": {
    params: {
      "slug": string;
    };
  };
  "/results": {
    params: {};
  };
  "/results/:attemptId": {
    params: {
      "attemptId": string;
    };
  };
  "/checkout/:productSlug": {
    params: {
      "productSlug": string;
    };
  };
  "/orders": {
    params: {};
  };
  "/orders/:orderNumber": {
    params: {
      "orderNumber": string;
    };
  };
  "/activate": {
    params: {};
  };
  "/profile/security": {
    params: {};
  };
  "/notifications": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/cms": {
    params: {};
  };
  "/admin/cms/templates": {
    params: {};
  };
  "/admin/cms/pages/:id": {
    params: {
      "id": string;
    };
  };
  "/admin/cms/preview/:pageId": {
    params: {
      "pageId": string;
    };
  };
  "/admin/cms/menus": {
    params: {};
  };
  "/admin/cms/forms": {
    params: {};
  };
  "/admin/appearance": {
    params: {};
  };
  "/admin/content": {
    params: {};
  };
  "/admin/content/:type/:id": {
    params: {
      "type": string;
      "id": string;
    };
  };
  "/admin/files": {
    params: {};
  };
  "/admin/videos": {
    params: {};
  };
  "/admin/entitlements": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
  "/admin/users/:id": {
    params: {
      "id": string;
    };
  };
  "/admin/analytics": {
    params: {};
  };
  "/admin/audit": {
    params: {};
  };
  "/admin/security": {
    params: {};
  };
  "/admin/announcements": {
    params: {};
  };
  "/admin/assessment": {
    params: {};
  };
  "/admin/assessment/questions/:id": {
    params: {
      "id": string;
    };
  };
  "/admin/assessment/exams/:id": {
    params: {
      "id": string;
    };
  };
  "/admin/commerce": {
    params: {};
  };
  "/admin/commerce/products/:id": {
    params: {
      "id": string;
    };
  };
  "/admin/commerce/orders/:id": {
    params: {
      "id": string;
    };
  };
  "/admin/commerce/batches/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/p/:slug" | "/programs" | "/programs/:slug" | "/subjects/:slug" | "/courses" | "/courses/:slug" | "/courses/:slug/units/:unitId" | "/products/:slug" | "/login" | "/register" | "/forgot-password" | "/reset-password" | "/set-locale" | "/logout" | "/theme.css" | "/favicon.ico" | "/learn/:courseSlug/:lessonSlug" | "/files/:id" | "/api/playback/:videoId" | "/beacons/progress" | "/api/exam-attempt" | "/webhooks/payments/:provider" | "/exams/:slug/attempt" | "/api/mock-stream/:videoId/:file" | "/dashboard" | "/profile" | "/exams" | "/exams/:slug" | "/results" | "/results/:attemptId" | "/checkout/:productSlug" | "/orders" | "/orders/:orderNumber" | "/activate" | "/profile/security" | "/notifications" | "/admin" | "/admin/cms" | "/admin/cms/templates" | "/admin/cms/pages/:id" | "/admin/cms/preview/:pageId" | "/admin/cms/menus" | "/admin/cms/forms" | "/admin/appearance" | "/admin/content" | "/admin/content/:type/:id" | "/admin/files" | "/admin/videos" | "/admin/entitlements" | "/admin/users" | "/admin/users/:id" | "/admin/analytics" | "/admin/audit" | "/admin/security" | "/admin/announcements" | "/admin/assessment" | "/admin/assessment/questions/:id" | "/admin/assessment/exams/:id" | "/admin/commerce" | "/admin/commerce/products/:id" | "/admin/commerce/orders/:id" | "/admin/commerce/batches/:id";
  };
  "routes/public/layout.tsx": {
    id: "public";
    page: "/" | "/p/:slug" | "/programs" | "/programs/:slug" | "/subjects/:slug" | "/courses" | "/courses/:slug" | "/courses/:slug/units/:unitId" | "/products/:slug" | "/login" | "/register" | "/forgot-password" | "/reset-password" | "/set-locale";
  };
  "routes/public/home.tsx": {
    id: "routes/public/home";
    page: "/";
  };
  "routes/p.$slug.tsx": {
    id: "routes/p.$slug";
    page: "/p/:slug";
  };
  "routes/public.programs.tsx": {
    id: "routes/public.programs";
    page: "/programs";
  };
  "routes/public.programs.$slug.tsx": {
    id: "routes/public.programs.$slug";
    page: "/programs/:slug";
  };
  "routes/public.subjects.$slug.tsx": {
    id: "routes/public.subjects.$slug";
    page: "/subjects/:slug";
  };
  "routes/public.courses.tsx": {
    id: "routes/public.courses";
    page: "/courses";
  };
  "routes/public.courses.$slug.tsx": {
    id: "routes/public.courses.$slug";
    page: "/courses/:slug";
  };
  "routes/public.courses.$slug.units.$unitId.tsx": {
    id: "routes/public.courses.$slug.units.$unitId";
    page: "/courses/:slug/units/:unitId";
  };
  "routes/public.products.$slug.tsx": {
    id: "routes/public.products.$slug";
    page: "/products/:slug";
  };
  "routes/public/login.tsx": {
    id: "routes/public/login";
    page: "/login";
  };
  "routes/public/register.tsx": {
    id: "routes/public/register";
    page: "/register";
  };
  "routes/public/forgot-password.tsx": {
    id: "routes/public/forgot-password";
    page: "/forgot-password";
  };
  "routes/public/reset-password.tsx": {
    id: "routes/public/reset-password";
    page: "/reset-password";
  };
  "routes/public/set-locale.tsx": {
    id: "routes/public/set-locale";
    page: "/set-locale";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/theme[.]css.tsx": {
    id: "routes/theme[.]css";
    page: "/theme.css";
  };
  "routes/favicon[.]ico.tsx": {
    id: "routes/favicon[.]ico";
    page: "/favicon.ico";
  };
  "routes/learn.$courseSlug.$lessonSlug.tsx": {
    id: "routes/learn.$courseSlug.$lessonSlug";
    page: "/learn/:courseSlug/:lessonSlug";
  };
  "routes/files.$id.tsx": {
    id: "routes/files.$id";
    page: "/files/:id";
  };
  "routes/api.playback.$videoId.tsx": {
    id: "routes/api.playback.$videoId";
    page: "/api/playback/:videoId";
  };
  "routes/beacons.progress.tsx": {
    id: "routes/beacons.progress";
    page: "/beacons/progress";
  };
  "routes/api.exam-attempt.tsx": {
    id: "routes/api.exam-attempt";
    page: "/api/exam-attempt";
  };
  "routes/webhooks.payments.$provider.tsx": {
    id: "routes/webhooks.payments.$provider";
    page: "/webhooks/payments/:provider";
  };
  "routes/student/exams.$slug.attempt.tsx": {
    id: "routes/student/exams.$slug.attempt";
    page: "/exams/:slug/attempt";
  };
  "routes/api.mock-stream.$videoId.$file.tsx": {
    id: "routes/api.mock-stream.$videoId.$file";
    page: "/api/mock-stream/:videoId/:file";
  };
  "routes/student/layout.tsx": {
    id: "student";
    page: "/dashboard" | "/profile" | "/exams" | "/exams/:slug" | "/results" | "/results/:attemptId" | "/checkout/:productSlug" | "/orders" | "/orders/:orderNumber" | "/activate" | "/profile/security" | "/notifications";
  };
  "routes/student/dashboard.tsx": {
    id: "routes/student/dashboard";
    page: "/dashboard";
  };
  "routes/student/profile.tsx": {
    id: "routes/student/profile";
    page: "/profile";
  };
  "routes/student/exams.tsx": {
    id: "routes/student/exams";
    page: "/exams";
  };
  "routes/student/exams.$slug.tsx": {
    id: "routes/student/exams.$slug";
    page: "/exams/:slug";
  };
  "routes/student/results.tsx": {
    id: "routes/student/results";
    page: "/results";
  };
  "routes/student/results.$attemptId.tsx": {
    id: "routes/student/results.$attemptId";
    page: "/results/:attemptId";
  };
  "routes/student/checkout.$productSlug.tsx": {
    id: "routes/student/checkout.$productSlug";
    page: "/checkout/:productSlug";
  };
  "routes/student/orders.tsx": {
    id: "routes/student/orders";
    page: "/orders";
  };
  "routes/student/orders.$orderNumber.tsx": {
    id: "routes/student/orders.$orderNumber";
    page: "/orders/:orderNumber";
  };
  "routes/student/activate.tsx": {
    id: "routes/student/activate";
    page: "/activate";
  };
  "routes/student/security.tsx": {
    id: "routes/student/security";
    page: "/profile/security";
  };
  "routes/student/notifications.tsx": {
    id: "routes/student/notifications";
    page: "/notifications";
  };
  "routes/admin/layout.tsx": {
    id: "admin-root";
    page: "/admin" | "/admin/cms" | "/admin/cms/templates" | "/admin/cms/pages/:id" | "/admin/cms/preview/:pageId" | "/admin/cms/menus" | "/admin/cms/forms" | "/admin/appearance" | "/admin/content" | "/admin/content/:type/:id" | "/admin/files" | "/admin/videos" | "/admin/entitlements" | "/admin/users" | "/admin/users/:id" | "/admin/analytics" | "/admin/audit" | "/admin/security" | "/admin/announcements" | "/admin/assessment" | "/admin/assessment/questions/:id" | "/admin/assessment/exams/:id" | "/admin/commerce" | "/admin/commerce/products/:id" | "/admin/commerce/orders/:id" | "/admin/commerce/batches/:id";
  };
  "routes/admin/home.tsx": {
    id: "routes/admin/home";
    page: "/admin";
  };
  "routes/admin.cms.tsx": {
    id: "routes/admin.cms";
    page: "/admin/cms";
  };
  "routes/admin.cms.templates.tsx": {
    id: "routes/admin.cms.templates";
    page: "/admin/cms/templates";
  };
  "routes/admin.cms.pages.$id.tsx": {
    id: "routes/admin.cms.pages.$id";
    page: "/admin/cms/pages/:id";
  };
  "routes/admin.cms.preview.$pageId.tsx": {
    id: "routes/admin.cms.preview.$pageId";
    page: "/admin/cms/preview/:pageId";
  };
  "routes/admin.cms.menus.tsx": {
    id: "routes/admin.cms.menus";
    page: "/admin/cms/menus";
  };
  "routes/admin.cms.forms.tsx": {
    id: "routes/admin.cms.forms";
    page: "/admin/cms/forms";
  };
  "routes/admin.appearance.tsx": {
    id: "routes/admin.appearance";
    page: "/admin/appearance";
  };
  "routes/admin.content.tsx": {
    id: "routes/admin.content";
    page: "/admin/content";
  };
  "routes/admin.content.$type.$id.tsx": {
    id: "routes/admin.content.$type.$id";
    page: "/admin/content/:type/:id";
  };
  "routes/admin.files.tsx": {
    id: "routes/admin.files";
    page: "/admin/files";
  };
  "routes/admin.videos.tsx": {
    id: "routes/admin.videos";
    page: "/admin/videos";
  };
  "routes/admin.entitlements.tsx": {
    id: "routes/admin.entitlements";
    page: "/admin/entitlements";
  };
  "routes/admin.users.tsx": {
    id: "routes/admin.users";
    page: "/admin/users";
  };
  "routes/admin.users.$id.tsx": {
    id: "routes/admin.users.$id";
    page: "/admin/users/:id";
  };
  "routes/admin.analytics.tsx": {
    id: "routes/admin.analytics";
    page: "/admin/analytics";
  };
  "routes/admin.audit.tsx": {
    id: "routes/admin.audit";
    page: "/admin/audit";
  };
  "routes/admin.security.tsx": {
    id: "routes/admin.security";
    page: "/admin/security";
  };
  "routes/admin.announcements.tsx": {
    id: "routes/admin.announcements";
    page: "/admin/announcements";
  };
  "routes/admin.assessment.tsx": {
    id: "routes/admin.assessment";
    page: "/admin/assessment";
  };
  "routes/admin.assessment.questions.$id.tsx": {
    id: "routes/admin.assessment.questions.$id";
    page: "/admin/assessment/questions/:id";
  };
  "routes/admin.assessment.exams.$id.tsx": {
    id: "routes/admin.assessment.exams.$id";
    page: "/admin/assessment/exams/:id";
  };
  "routes/admin.commerce.tsx": {
    id: "routes/admin.commerce";
    page: "/admin/commerce";
  };
  "routes/admin.commerce.products.$id.tsx": {
    id: "routes/admin.commerce.products.$id";
    page: "/admin/commerce/products/:id";
  };
  "routes/admin.commerce.orders.$id.tsx": {
    id: "routes/admin.commerce.orders.$id";
    page: "/admin/commerce/orders/:id";
  };
  "routes/admin.commerce.batches.$id.tsx": {
    id: "routes/admin.commerce.batches.$id";
    page: "/admin/commerce/batches/:id";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "public": typeof import("./app/routes/public/layout.tsx");
  "routes/public/home": typeof import("./app/routes/public/home.tsx");
  "routes/p.$slug": typeof import("./app/routes/p.$slug.tsx");
  "routes/public.programs": typeof import("./app/routes/public.programs.tsx");
  "routes/public.programs.$slug": typeof import("./app/routes/public.programs.$slug.tsx");
  "routes/public.subjects.$slug": typeof import("./app/routes/public.subjects.$slug.tsx");
  "routes/public.courses": typeof import("./app/routes/public.courses.tsx");
  "routes/public.courses.$slug": typeof import("./app/routes/public.courses.$slug.tsx");
  "routes/public.courses.$slug.units.$unitId": typeof import("./app/routes/public.courses.$slug.units.$unitId.tsx");
  "routes/public.products.$slug": typeof import("./app/routes/public.products.$slug.tsx");
  "routes/public/login": typeof import("./app/routes/public/login.tsx");
  "routes/public/register": typeof import("./app/routes/public/register.tsx");
  "routes/public/forgot-password": typeof import("./app/routes/public/forgot-password.tsx");
  "routes/public/reset-password": typeof import("./app/routes/public/reset-password.tsx");
  "routes/public/set-locale": typeof import("./app/routes/public/set-locale.tsx");
  "routes/logout": typeof import("./app/routes/logout.tsx");
  "routes/theme[.]css": typeof import("./app/routes/theme[.]css.tsx");
  "routes/favicon[.]ico": typeof import("./app/routes/favicon[.]ico.tsx");
  "routes/learn.$courseSlug.$lessonSlug": typeof import("./app/routes/learn.$courseSlug.$lessonSlug.tsx");
  "routes/files.$id": typeof import("./app/routes/files.$id.tsx");
  "routes/api.playback.$videoId": typeof import("./app/routes/api.playback.$videoId.tsx");
  "routes/beacons.progress": typeof import("./app/routes/beacons.progress.tsx");
  "routes/api.exam-attempt": typeof import("./app/routes/api.exam-attempt.tsx");
  "routes/webhooks.payments.$provider": typeof import("./app/routes/webhooks.payments.$provider.tsx");
  "routes/student/exams.$slug.attempt": typeof import("./app/routes/student/exams.$slug.attempt.tsx");
  "routes/api.mock-stream.$videoId.$file": typeof import("./app/routes/api.mock-stream.$videoId.$file.tsx");
  "student": typeof import("./app/routes/student/layout.tsx");
  "routes/student/dashboard": typeof import("./app/routes/student/dashboard.tsx");
  "routes/student/profile": typeof import("./app/routes/student/profile.tsx");
  "routes/student/exams": typeof import("./app/routes/student/exams.tsx");
  "routes/student/exams.$slug": typeof import("./app/routes/student/exams.$slug.tsx");
  "routes/student/results": typeof import("./app/routes/student/results.tsx");
  "routes/student/results.$attemptId": typeof import("./app/routes/student/results.$attemptId.tsx");
  "routes/student/checkout.$productSlug": typeof import("./app/routes/student/checkout.$productSlug.tsx");
  "routes/student/orders": typeof import("./app/routes/student/orders.tsx");
  "routes/student/orders.$orderNumber": typeof import("./app/routes/student/orders.$orderNumber.tsx");
  "routes/student/activate": typeof import("./app/routes/student/activate.tsx");
  "routes/student/security": typeof import("./app/routes/student/security.tsx");
  "routes/student/notifications": typeof import("./app/routes/student/notifications.tsx");
  "admin-root": typeof import("./app/routes/admin/layout.tsx");
  "routes/admin/home": typeof import("./app/routes/admin/home.tsx");
  "routes/admin.cms": typeof import("./app/routes/admin.cms.tsx");
  "routes/admin.cms.templates": typeof import("./app/routes/admin.cms.templates.tsx");
  "routes/admin.cms.pages.$id": typeof import("./app/routes/admin.cms.pages.$id.tsx");
  "routes/admin.cms.preview.$pageId": typeof import("./app/routes/admin.cms.preview.$pageId.tsx");
  "routes/admin.cms.menus": typeof import("./app/routes/admin.cms.menus.tsx");
  "routes/admin.cms.forms": typeof import("./app/routes/admin.cms.forms.tsx");
  "routes/admin.appearance": typeof import("./app/routes/admin.appearance.tsx");
  "routes/admin.content": typeof import("./app/routes/admin.content.tsx");
  "routes/admin.content.$type.$id": typeof import("./app/routes/admin.content.$type.$id.tsx");
  "routes/admin.files": typeof import("./app/routes/admin.files.tsx");
  "routes/admin.videos": typeof import("./app/routes/admin.videos.tsx");
  "routes/admin.entitlements": typeof import("./app/routes/admin.entitlements.tsx");
  "routes/admin.users": typeof import("./app/routes/admin.users.tsx");
  "routes/admin.users.$id": typeof import("./app/routes/admin.users.$id.tsx");
  "routes/admin.analytics": typeof import("./app/routes/admin.analytics.tsx");
  "routes/admin.audit": typeof import("./app/routes/admin.audit.tsx");
  "routes/admin.security": typeof import("./app/routes/admin.security.tsx");
  "routes/admin.announcements": typeof import("./app/routes/admin.announcements.tsx");
  "routes/admin.assessment": typeof import("./app/routes/admin.assessment.tsx");
  "routes/admin.assessment.questions.$id": typeof import("./app/routes/admin.assessment.questions.$id.tsx");
  "routes/admin.assessment.exams.$id": typeof import("./app/routes/admin.assessment.exams.$id.tsx");
  "routes/admin.commerce": typeof import("./app/routes/admin.commerce.tsx");
  "routes/admin.commerce.products.$id": typeof import("./app/routes/admin.commerce.products.$id.tsx");
  "routes/admin.commerce.orders.$id": typeof import("./app/routes/admin.commerce.orders.$id.tsx");
  "routes/admin.commerce.batches.$id": typeof import("./app/routes/admin.commerce.batches.$id.tsx");
};